# Generated by Django 5.2.7 on 2025-10-14 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number: optional '+' followed by 9 to 15 digits. Spaces are allowed.", regex='^\\+?\\s*(?:\\d\\s*){9,15}$')])),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClubManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('club_name', models.CharField(max_length=50)),
                ('club_location', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number: optional '+' followed by 9 to 15 digits. Spaces are allowed.", regex='^\\+?\\s*(?:\\d\\s*){9,15}$')])),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number: optional '+' followed by 9 to 15 digits. Spaces are allowed.", regex='^\\+?\\s*(?:\\d\\s*){9,15}$')])),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number: optional '+' followed by 9 to 15 digits. Spaces are allowed.", regex='^\\+?\\s*(?:\\d\\s*){9,15}$')])),
                ('email', models.EmailField(max_length=50)),
                ('subscription_end', models.DateField()),
            ],
        ),
    ]
