# Generated by Django 5.2.7 on 2025-10-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_judge_user_location_user_team_name_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_name',
        ),
        migrations.AddField(
            model_name='user',
            name='club_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='club_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer'), ('CLUB MANAGER', 'Club Manager'), ('JUDGE', 'Judge')], max_length=50),
        ),
    ]
