# Generated by Django 5.2.7 on 2025-10-15 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_location_remove_user_team_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubManager',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number: optional '+' followed by 9 to 15 digits. Spaces are allowed.", regex='^\\+?\\s*(?:\\d\\s*){9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer'), ('CLUB_MANAGER', 'Club Manager'), ('JUDGE', 'Judge')], default='ADMIN', max_length=50),
        ),
    ]
