# Generated by Django 5.2.7 on 2025-10-15 14:26

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choreography', models.CharField(max_length=50)),
                ('length', models.TimeField()),
                ('choreograph', models.CharField(max_length=50)),
                ('music', models.FileField(upload_to='')),
                ('age_category', models.CharField(choices=[('DJECA', 'Djeca'), ('JUNIORI', 'Juniori'), ('SENIORI', 'Seniori')], default='DJECA', max_length=50)),
                ('style_category', models.CharField(choices=[('BALET', 'Balet'), ('HIPHOP', 'Hip Hop'), ('JAZZ', 'Jazz'), ('STEP', 'Step'), ('BREAK', 'Break')], default='BALET', max_length=50)),
                ('group_size_category', models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('MALA_GRUPA', 'Mala grupa'), ('FORMACIJA', 'Formacija')], default='SOLO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('age_categories', multiselectfield.db.fields.MultiSelectField(choices=[('DJECA', 'Djeca'), ('JUNIORI', 'Juniori'), ('SENIORI', 'Seniori')], default=['DJECA'], max_length=50)),
                ('style_categories', multiselectfield.db.fields.MultiSelectField(choices=[('BALET', 'Balet'), ('HIPHOP', 'Hip Hop'), ('JAZZ', 'Jazz'), ('STEP', 'Step'), ('BREAK', 'Break')], default=['BALET'], max_length=50)),
                ('group_size_categories', multiselectfield.db.fields.MultiSelectField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('MALA_GRUPA', 'Mala grupa'), ('FORMACIJA', 'Formacija')], default=['SOLO'], max_length=50)),
            ],
        ),
    ]
