# Generated by Django 5.2.7 on 2025-10-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('DJECA', 'djeca'), ('JUNIORI', 'juniori'), ('SENIORI', 'seniori')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size_category', models.CharField(choices=[('SOLO', 'solo'), ('DUO', 'duo'), ('MALA GRUPA', 'mala grupa'), ('FORMACIJA', 'formacija')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_category', models.CharField(choices=[('BALET', 'balet'), ('HIP HOP', 'hip hop'), ('JAZZ', 'jazz'), ('STEP', 'step'), ('BREAK', 'break')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('age_categories', models.ManyToManyField(to='competitions.agecategory')),
                ('group_size_categories', models.ManyToManyField(to='competitions.groupsizecategory')),
                ('style_categories', models.ManyToManyField(to='competitions.stylecategory')),
            ],
        ),
    ]
