# Generated by Django 5.2.7 on 2025-10-15 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='club_manager',
            field=models.ForeignKey(limit_choices_to={'role': 'CLUB_MANAGER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'role': 'ORGANIZER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appearance',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='competitions.competition'),
        ),
    ]
