# Generated by Django 5.2.7 on 2025-10-11 20:10

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_competition_age_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='group_size_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('MALA_GRUPA', 'Mala grupa'), ('FORMACIJA', 'Formacija')], default=['SOLO'], max_length=50),
        ),
    ]
