# Generated by Django 5.2.7 on 2025-10-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competition_organizer_appearance'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='club_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='users.clubmanager'),
        ),
    ]
