# Generated by Django 5.2.7 on 2025-10-11 20:09

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='age_categories',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='group_size_categories',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='style_categories',
        ),
        migrations.DeleteModel(
            name='AgeCategory',
        ),
        migrations.AddField(
            model_name='competition',
            name='age_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DJECA', 'Djeca'), ('JUNIORI', 'Juniori'), ('SENIORI', 'Seniori')], default=['DJECA'], max_length=50),
        ),
        migrations.DeleteModel(
            name='GroupSizeCategory',
        ),
        migrations.AddField(
            model_name='competition',
            name='group_size_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('MALA_GRUPA', 'Mala grupa'), ('FORMACIJA', 'Formacija')], default=['Solo'], max_length=50),
        ),
        migrations.DeleteModel(
            name='StyleCategory',
        ),
        migrations.AddField(
            model_name='competition',
            name='style_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BALET', 'Balet'), ('HIPHOP', 'Hip Hop'), ('JAZZ', 'Jazz'), ('STEP', 'Step'), ('BREAK', 'Break')], default=['BALET'], max_length=100),
        ),
    ]
