# Generated by Django 5.2.7 on 2025-10-11 20:18

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_group_size_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='style_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BALET', 'Balet'), ('HIPHOP', 'Hip Hop'), ('JAZZ', 'Jazz'), ('STEP', 'Step'), ('BREAK', 'Break')], default=['BALET'], max_length=50),
        ),
    ]
