# Generated by Django 5.2.7 on 2025-10-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_competition_style_categories'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='users.organizer'),
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choreography', models.CharField(max_length=50)),
                ('length', models.TimeField()),
                ('choreograph', models.CharField(max_length=50)),
                ('music', models.FileField(upload_to='')),
                ('age_category', models.CharField(choices=[('DJECA', 'Djeca'), ('JUNIORI', 'Juniori'), ('SENIORI', 'Seniori')], default='DJECA', max_length=50)),
                ('style_category', models.CharField(choices=[('BALET', 'Balet'), ('HIPHOP', 'Hip Hop'), ('JAZZ', 'Jazz'), ('STEP', 'Step'), ('BREAK', 'Break')], default='BALET', max_length=50)),
                ('group_size_category', models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('MALA_GRUPA', 'Mala grupa'), ('FORMACIJA', 'Formacija')], default='SOLO', max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='competitions.competition')),
            ],
        ),
    ]
